# Generated by Django 3.2.3 on 2021-06-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_people', models.IntegerField()),
                ('is_seaview', models.BooleanField()),
                ('is_highseason', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_nb', models.SmallIntegerField(unique=True)),
                ('rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.rate')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('hotel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='visitors.hotel')),
                ('room_id', models.ManyToManyField(null=True, to='visitors.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('passport_nb', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors.country')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('end_day', models.DurationField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('cancelation_date', models.DateTimeField(blank=True, null=True)),
                ('discount', models.FloatField(default=0.0)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.guest')),
                ('room_id', models.ManyToManyField(blank=True, null=True, related_name='rooms', to='visitors.Room')),
            ],
        ),
    ]
