# Generated by Django 3.2.3 on 2021-06-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20210603_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors.rate'),
        ),
    ]
